### PR TITLE
Branch fix duplicte lesson timeslot

### LINKED ISSUE #47: Fix duplicate lesson timing bug

### PR DESCRIPTION
**Pull request by Zerolegacy**
Fixes #47

### CODE REVIEW

File: src/main/java/seedu/tuitionbook/logic/commands/LessonAddCommand.java [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+    private final Index index;
+    private final List<Lesson> lessonsToAdd;
+
+    /**
+     * @param index of the person in the filtered person list to add lessons to
+     * @param lessonsToAdd lessons that the user wants to add to the person
+     */
+    public LessonAddCommand(Index index, List<Lesson> lessonsToAdd) {
+        requireNonNull(index);
+        requireNonNull(lessonsToAdd);
```
Comment (RT0118) [inline src/main/java/seedu/tuitionbook/logic/commands/LessonAddCommand.java:51]: Good use of requireNonNull to ensure index and lessonsToAdd are guaranteed to exist

File: src/main/java/seedu/tuitionbook/logic/commands/LessonAddCommand.java [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+        assert !lessonsToAdd.isEmpty();
```
Comment (RT0118) [inline src/main/java/seedu/tuitionbook/logic/commands/LessonAddCommand.java:52]: Nice to see the use of assert to ensure arguments are not empty

File: src/main/java/seedu/tuitionbook/model/AddressBook.java [hunk 3]
```diff
@@ -94,6 +95,28 @@ public void removePerson(Person key) {
...
 
+    /**
+     * Returns true if a lesson with the same timingexists in the address book.
+     */
+    public boolean hasLesson(List<Lesson> lessons) {
+        requireNonNull(lessons);
+        ObservableList<Person> personList = getPersonList();
+        List<String> lessonsToCheck = lessons.stream()
+                .map(lesson -> lesson.getDatetimeAsString())
+                .toList();
```
Comment (RT0118) [inline src/main/java/seedu/tuitionbook/model/AddressBook.java:106]: I like your use of streams here, it makes the code more readable

File: src/test/java/seedu/tuitionbook/logic/commands/LessonAddCommandTest.java [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+
+        // null -> returns false
+        assertFalse(addFirstCommand.equals(null));
+
+        // different types -> returns false
+        assertFalse(addFirstCommand.equals(new ClearCommand()));
+
+        // different index -> returns false
+        assertFalse(addFirstCommand.equals(new LessonAddCommand(INDEX_SECOND_PERSON, lessonsToAdd)));
+    }
```
Comment (RT0118) [inline src/test/java/seedu/tuitionbook/logic/commands/LessonAddCommandTest.java:113]: Good to see that methods are tested extensively!

**Review by RT0118 — COMMENTED** [review]
LGTM!
